// import './bases/tipos/tiposDeDatos';
// import './bases/funciones/funciones';
// import './bases/funciones/parametrosObligatorios';
// import './bases/funciones/parametrosOpcionales';
// import './bases/funciones/parametrosPorDefecto';
// import './bases/funciones/parametroRest';
// import './bases/funciones/tipoFuncion';
// import './bases/objetos/objetosLiterales';
// import './bases/objetos/tipos';
// import './bases/objetos/tiposMultiples';
// import './bases/ES6/desestructuracionObjetos';
import './bases/ES6/desestructuracionArray';